# Generated by Django 4.0.6 on 2022-09-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_borrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='image',
            field=models.ImageField(default='books/img/cover.png', upload_to='books/img/'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
