# Generated by Django 4.0.6 on 2022-09-03 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_borrow_image_alter_borrow_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow',
            old_name='book',
            new_name='borrowed_book',
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.borrow'),
        ),
    ]
