# Generated by Django 4.0.6 on 2022-09-03 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_book_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='borrowed_book',
        ),
    ]
