# Generated by Django 4.0.6 on 2022-09-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_remove_borrow_book_book_status_alter_borrow_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='status',
            field=models.CharField(choices=[('D', 'Dostępna'), ('W', 'Wypożyczona')], default=('D', 'Dostępna'), max_length=50),
        ),
    ]
