# Generated by Django 4.0.6 on 2022-09-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_alter_borrow_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('D', 'Dostępna'), ('W', 'Wypożyczona')], default='D', max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Borrow',
        ),
    ]
