# Generated by Django 4.0.6 on 2022-09-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_alter_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('Dostępna', 'Dostępna'), ('Wypożyczona', 'Wypożyczona')], default='Dostępna', max_length=50, null=True),
        ),
    ]
