# Generated by Django 4.0.6 on 2022-09-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
