# Generated by Django 4.0.6 on 2022-09-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_borrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='slug',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
