# Generated by Django 4.0.6 on 2022-09-06 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0022_borrow_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='slug',
        ),
    ]
