# Generated by Django 4.0.6 on 2022-09-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0023_remove_borrow_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='returned',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
