# Generated by Django 4.0.6 on 2022-09-14 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0024_borrow_returned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
    ]
